# SCREEN SETTINGS
SCREEN_W = 128
SCREEN_H = 96
FPS_LIMIT = 20

# FONT SETTINGS
MAIN_FONT = "_assets/Fonts/terminal16x16_gs_ro.png"
MAIN_TILES = "_assets/Tiles/EternalFacadeTiles.png"
NUM_TILES_WIDE = 64
NUM_TILES_HIGH = 95

# DUNGEON SETTINGS
DUNGEON_WIDTH = 80
DUNGEON_HEIGHT = 64

DUNGEON_TILE_SIZE = 4

MAX_MAP_W = 250
MAX_MAP_H = 250

MIN_ROOM_SIZE = 3
MAX_ROOM_SIZE = 10

# TEXT LOG SETTINGS
TL_WIDTH = 80
TL_HEIGHT = 32

# STATS_INFO SETTINGS
SI_WIDTH = 48
SI_HEIGHT = 56

# INVENTORY SETTINGS
INV_WIDTH = 48
INV_HEIGHT = 40
